<a href="https://colab.research.google.com/github/Ivan8Garcia/Proyectos_MachineLearning/blob/main/Aula_2_Python_Inteligencia_Artificial_Aplicada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aula 2**

In [ ]:
import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
respuesta = client.models.generate_content(model="gemini-2.5-flash", contents="Que es la IA")

In [ ]:
print(respuesta.text)

La **Inteligencia Artificial (IA)** es un campo de la informática que se enfoca en crear sistemas o máquinas que pueden realizar tareas que normalmente requieren inteligencia humana.

En esencia, la IA busca imitar o simular procesos de pensamiento y capacidades cognitivas humanas como:

1.  **Aprendizaje:** Adquirir información y reglas para usarla (ej. mediante el "Machine Learning" o Aprendizaje Automático, donde los sistemas aprenden de los datos sin ser programados explícitamente).
2.  **Razonamiento:** Usar esas reglas para llegar a conclusiones aproximadas o definitivas.
3.  **Percepción:** Comprender el entorno a través de los sentidos (visión por computadora, reconocimiento de voz).
4.  **Comprensión del lenguaje:** Entender, interpretar y generar lenguaje humano (Procesamiento del Lenguaje Natural - PLN).
5.  **Resolución de problemas:** Encontrar soluciones a problemas específicos.
6.  **Toma de decisiones:** Elegir la mejor opción entre varias posibilidades.

**¿Cómo funciona la IA (de forma simplificada)?**

Los sistemas de IA utilizan algoritmos complejos y grandes volúmenes de datos (Big Data) para:

*   **Identificar patrones:** Encontrar relaciones y estructuras en los datos.
*   **Hacer predicciones:** Basarse en los patrones identificados.
*   **Tomar decisiones:** Actuar según las predicciones o reglas programadas.
*   **Mejorar con la experiencia:** Cuantos más datos procesa y más interacciones tiene, más "inteligente" o precisa se vuelve.

**Tipos de IA:**

Es importante diferenciar entre los tipos de IA que existen actualmente y los que son más bien conceptos futuros:

1.  **IA Débil o Estrecha (ANI - Artificial Narrow Intelligence):** Es el tipo de IA que existe hoy en día. Está diseñada y entrenada para realizar una tarea específica.
    *   **Ejemplos:** Asistentes de voz (Siri, Alexa), sistemas de recomendación (Netflix, Amazon), filtros de spam, coches autónomos (en su función de conducir), reconocimiento facial, programas de ajedrez.
    *   *Característica clave:* No tiene conciencia ni una inteligencia general como la humana. Solo sobresale en su dominio particular.

2.  **IA Fuerte o General (AGI - Artificial General Intelligence):** Es una IA hipotética que tendría la capacidad de entender, aprender y aplicar la inteligencia en cualquier tarea intelectual que un ser humano pueda hacer. Podría resolver problemas, aprender de cualquier experiencia y razonar de forma general.
    *   *Estado actual:* Es un objetivo de investigación a largo plazo y aún no existe.

3.  **Superinteligencia Artificial (ASI - Artificial Superintelligence):** Una IA hipotética que no solo sería tan inteligente como los humanos, sino que superaría con creces la inteligencia humana en todos los aspectos, incluida la creatividad científica, la sabiduría general y las habilidades sociales.
    *   *Estado actual:* Es puramente especulativa y de ciencia ficción por ahora.

**Ejemplos de dónde encuentras la IA en tu día a día:**

*   **Teléfonos inteligentes:** Reconocimiento facial, asistentes de voz, teclados predictivos.
*   **Plataformas de streaming:** Sugerencias de películas o música personalizadas.
*   **Compras online:** Recomendaciones de productos.
*   **Navegadores GPS:** Optimización de rutas.
*   **Bancos:** Detección de fraudes, chatbots de atención al cliente.
*   **Medicina:** Diagnóstico de enfermedades, desarrollo de fármacos.
*   **Vehículos:** Conducción autónoma, sistemas de seguridad.
*   **IA Generativa:** Como yo mismo (ChatGPT), que puedo generar texto, imágenes, código, etc., a partir de una solicitud.

En resumen, la IA es una tecnología transformadora que permite a las máquinas realizar tareas inteligentes, automatizar procesos, analizar grandes volúmenes de datos y, en última instancia, resolver problemas complejos y mejorar la eficiencia en casi todos los aspectos de nuestra vida.

In [ ]:
print("*********************")

*********************

In [ ]:
n = 1

while n <=100:
  print("*")
  n=n+1
print("Ya salimos del while")

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
Ya salimos del while

In [ ]:
chat = client.chats.create(model="gemini-2.5-flash")

In [ ]:
respuesta = chat.send_message("Que es la IA")

In [ ]:
print(respuesta)

sdk_http_response=HttpResponse(
  headers=<dict len=11>
) candidates=[Candidate(
  content=Content(
    parts=[
      Part(
        text="""La **Inteligencia Artificial (IA)** es un campo de la informática que se enfoca en crear máquinas y sistemas capaces de realizar tareas que, normalmente, requieren inteligencia humana. En esencia, busca simular procesos de inteligencia humana en computadoras.

**¿Qué significa esto en la práctica?**

Significa que las máquinas pueden:

1.  **Aprender:** Adquirir conocimientos y habilidades a través de datos y experiencia, en lugar de ser programadas explícitamente para cada tarea. Esto se conoce como **Aprendizaje Automático (Machine Learning)**, y es una rama fundamental de la IA.
2.  **Razonar:** Utilizar la lógica para tomar decisiones, resolver problemas y sacar conclusiones.
3.  **Entender y Procesar Lenguaje Natural:** Interpretar el lenguaje humano (hablado o escrito), lo que permite interactuar con asistentes de voz, chatbots, etc. (Esto es **Procesamiento del Lenguaje Natural - PLN**).
4.  **Percibir:** Interpretar información del mundo a través de sensores, como imágenes (Visión por Computadora) o sonido.
5.  **Planificar:** Establecer metas y estrategias para alcanzarlas.
6.  **Mover y Manipular Objetos:** En el contexto de la robótica, la IA permite a los robots interactuar con su entorno de manera inteligente.

**Ramas y Conceptos Clave de la IA:**

*   **Machine Learning (Aprendizaje Automático):** Es la rama más popular de la IA. Se centra en algoritmos que permiten a las computadoras aprender de los datos sin ser programadas explícitamente. Por ejemplo, si le muestras a una IA miles de fotos de gatos, aprenderá a identificar gatos en nuevas fotos.
*   **Deep Learning (Aprendizaje Profundo):** Una subcategoría del Machine Learning que utiliza redes neuronales artificiales con múltiples capas (inspiradas en el cerebro humano) para aprender patrones complejos de grandes volúmenes de datos. Es la base de muchas de las IA más avanzadas de hoy (reconocimiento facial, vehículos autónomos).
*   **Procesamiento del Lenguaje Natural (PLN/NLP):** Permite a las máquinas entender, interpretar y generar lenguaje humano. Es lo que hace posible que los asistentes de voz respondan a tus preguntas o que los traductores automáticos funcionen.
*   **Visión por Computadora (Computer Vision):** Permite a las máquinas "ver" e interpretar imágenes y videos, como el reconocimiento facial, la detección de objetos o la lectura de matrículas.
*   **Robótica:** Aunque no toda la robótica es IA, muchas aplicaciones de robots usan la IA para la navegación, la toma de decisiones o la interacción inteligente con el entorno.

**¿Dónde encuentras la IA en tu vida diaria?**

*   **Asistentes de voz:** Siri, Alexa, Google Assistant.
*   **Sistemas de recomendación:** Netflix (qué ver), Amazon (qué comprar), Spotify (qué escuchar).
*   **Filtros de spam** en tu correo electrónico.
*   **Reconocimiento facial** en tu smartphone o redes sociales.
*   **Vehículos autónomos** (coches sin conductor).
*   **Chatbots** de atención al cliente.
*   **Traducción automática** (Google Translate).
*   **Diagnóstico médico** asistido por IA.
*   **Motores de búsqueda** (para entender tu consulta).

En resumen, la IA es el esfuerzo por dotar a las máquinas de capacidades cognitivas similares a las humanas, permitiéndoles aprender, razonar, percibir y tomar decisiones de forma autónoma. Está transformando rápidamente casi todos los aspectos de nuestra sociedad."""
      ),
    ],
    role='model'
  ),
  finish_reason=<FinishReason.STOP: 'STOP'>,
  index=0
)] create_time=None model_version='gemini-2.5-flash' prompt_feedback=None response_id='xlk4aq7YHuu-_uMPg7Cv2Ag' usage_metadata=GenerateContentResponseUsageMetadata(
  candidates_token_count=792,
  prompt_token_count=5,
  prompt_tokens_details=[
    ModalityTokenCount(
      modality=<MediaModality.TEXT: 'TEXT'>,
      token_count=5
    ),
  ],
  thoughts_token_count=854,
  total_token_count=1651
) automatic_function_calling_history=[] parsed=None

In [ ]:
respuesta =chat.send_message("Cuando se lanzo chatGPT")
print(respuesta.text)

ChatGPT fue lanzado al público por OpenAI el **30 de noviembre de 2022**.

In [ ]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='Que es la IA'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""La **Inteligencia Artificial (IA)** es un campo de la informática que se enfoca en crear máquinas y sistemas capaces de realizar tareas que, normalmente, requieren inteligencia humana. En esencia, busca simular procesos de inteligencia humana en computadoras.

 **¿Qué significa esto en la práctica?**

 Significa que las máquinas pueden:

 1.  **Aprender:** Adquirir conocimientos y habilidades a través de datos y experiencia, en lugar de ser programadas explícitamente para cada tarea. Esto se conoce como **Aprendizaje Automático (Machine Learning)**, y es una rama fundamental de la IA.
 2.  **Razonar:** Utilizar la lógica para tomar decisiones, resolver problemas y sacar conclusiones.
 3.  **Entender y Procesar Lenguaje Natural:** Interpretar el lenguaje humano (hablado o escrito), lo que permite interactuar con asistentes de voz, chatbots, etc. (Esto es **Procesamiento del Lenguaje Natural - PLN**).
 4.  **Percibir:** Interpretar información del mundo a través de sensores, como imágenes (Visión por Computadora) o sonido.
 5.  **Planificar:** Establecer metas y estrategias para alcanzarlas.
 6.  **Mover y Manipular Objetos:** En el contexto de la robótica, la IA permite a los robots interactuar con su entorno de manera inteligente.

 **Ramas y Conceptos Clave de la IA:**

 *   **Machine Learning (Aprendizaje Automático):** Es la rama más popular de la IA. Se centra en algoritmos que permiten a las computadoras aprender de los datos sin ser programadas explícitamente. Por ejemplo, si le muestras a una IA miles de fotos de gatos, aprenderá a identificar gatos en nuevas fotos.
 *   **Deep Learning (Aprendizaje Profundo):** Una subcategoría del Machine Learning que utiliza redes neuronales artificiales con múltiples capas (inspiradas en el cerebro humano) para aprender patrones complejos de grandes volúmenes de datos. Es la base de muchas de las IA más avanzadas de hoy (reconocimiento facial, vehículos autónomos).
 *   **Procesamiento del Lenguaje Natural (PLN/NLP):** Permite a las máquinas entender, interpretar y generar lenguaje humano. Es lo que hace posible que los asistentes de voz respondan a tus preguntas o que los traductores automáticos funcionen.
 *   **Visión por Computadora (Computer Vision):** Permite a las máquinas "ver" e interpretar imágenes y videos, como el reconocimiento facial, la detección de objetos o la lectura de matrículas.
 *   **Robótica:** Aunque no toda la robótica es IA, muchas aplicaciones de robots usan la IA para la navegación, la toma de decisiones o la interacción inteligente con el entorno.

 **¿Dónde encuentras la IA en tu vida diaria?**

 *   **Asistentes de voz:** Siri, Alexa, Google Assistant.
 *   **Sistemas de recomendación:** Netflix (qué ver), Amazon (qué comprar), Spotify (qué escuchar).
 *   **Filtros de spam** en tu correo electrónico.
 *   **Reconocimiento facial** en tu smartphone o redes sociales.
 *   **Vehículos autónomos** (coches sin conductor).
 *   **Chatbots** de atención al cliente.
 *   **Traducción automática** (Google Translate).
 *   **Diagnóstico médico** asistido por IA.
 *   **Motores de búsqueda** (para entender tu consulta).

 En resumen, la IA es el esfuerzo por dotar a las máquinas de capacidades cognitivas similares a las humanas, permitiéndoles aprender, razonar, percibir y tomar decisiones de forma autónoma. Está transformando rápidamente casi todos los aspectos de nuestra sociedad."""
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='Cuando se lanzo chatGPT'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text='ChatGPT fue lanzado al público por OpenAI el **30 de noviembre de 2022**.'
     ),
   ],
   role='model'
 )]

In [ ]:
prompt = input("Ingrese su pregunta: ")

while prompt != "fin":
  respuesta=chat.send_message(prompt)
  print(respuesta.text)
  prompt = input("Ingrese su pregunta (fin para terminar): ")

Ingrese su pregunta: fin

In [ ]:
nombres = ["Juan","Laura","Fernando","Josefina","Pedro"]
# pos.       0       1         2          3        4
print(nombres)

['Juan', 'Laura', 'Fernando', 'Josefina', 'Pedro']

In [ ]:
print("El quinto elemento es:",nombres[4])

El quinto elemento es: Pedro

In [ ]:
promedios = [8.5,6.5,7.3,9.5,6.3,2.5,4.8]
print(promedios[3])

9.5

In [ ]:
n=0 #1

while n < len(promedios):
  promedios[n]=promedios[n]+1
  if promedios[n]>10:
     promedios[n]=10
  n=n+1
print("Los promedios mejorados son:",promedios)

Los promedios mejorados son: [9.5, 7.5, 8.3, 10, 7.3, 3.5, 5.8]

In [ ]:
print("Cantidad de elementos en la lista:",len(promedios))

Cantidad de elementos en la lista: 7

In [ ]:
promedios[-2]

3.5

In [ ]:
nombres=["Maria Silva","Fernanda Castro","Juan Perez","Rodrigo Feliz","Juana Lala"]
print(nombres)

nombres[:3]

['Maria Silva', 'Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juana Lala']

['Maria Silva', 'Fernanda Castro', 'Juan Perez']

In [ ]:
nombres.append("Rogelio Rodriguez")
print(nombres)

['Maria Silva', 'Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juana Lala', 'Rogelio Rodriguez']

In [ ]:
print("Cantidad de elementos:",len(nombres))

Cantidad de elementos: 6

In [ ]:
nombres.extend(["Mateo Perez","Laura Fernan"])
print(nombres)

['Maria Silva', 'Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juana Lala', 'Rogelio Rodriguez', 'Mateo Perez', 'Laura Fernan']

In [ ]:
nombres.append(["Juan Oroz","Pedro Pereyra"])

In [ ]:
print(nombres)

['Maria Silva', 'Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juana Lala', 'Rogelio Rodriguez', 'Mateo Perez', 'Laura Fernan', ['Juan Oroz', 'Pedro Pereyra']]

In [ ]:
nombres[8][1]

'Pedro Pereyra'

In [ ]:
nombres[-1][-1]

'Pedro Pereyra'

In [ ]:
nombres.remove("Maria Silva")

In [ ]:
nombres

['Fernanda Castro',
 'Juan Perez',
 'Rodrigo Feliz',
 'Juana Lala',
 'Rogelio Rodriguez',
 'Mateo Perez',
 'Laura Fernan',
 ['Juan Oroz', 'Pedro Pereyra']]

In [ ]:
nombres.pop()
nombres

['Fernanda Castro',
 'Juan Perez',
 'Rodrigo Feliz',
 'Juana Lala',
 'Rogelio Rodriguez',
 'Mateo Perez',
 'Laura Fernan']

In [ ]:
nombres.pop(2)
nombres

['Fernanda Castro',
 'Juan Perez',
 'Juana Lala',
 'Rogelio Rodriguez',
 'Mateo Perez',
 'Laura Fernan']

Diccionarios:

estudiantes=["clave":valor]

In [ ]:
nombres=["Maria Silva","Fernanda Castro","Juan Perez","Rodrigo Feliz","Juana Lala"]
promedios = [8.5,6.5,7.3,9.5,6.3,2.5,4.8]

estudiantes = {
    "Maria Silva":8.5,
    "Fernanda Castro":6.5,
    "Juan Perez":7.3,
    "Rodrigo Feliz":6.3,
    "Juaan Lala":2.5
}

print(nombres)
print(promedios)
print(estudiantes)

['Maria Silva', 'Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juana Lala']
[8.5, 6.5, 7.3, 9.5, 6.3, 2.5, 4.8]
{'Maria Silva': 8.5, 'Fernanda Castro': 6.5, 'Juan Perez': 7.3, 'Rodrigo Feliz': 6.3, 'Juaan Lala': 2.5}

In [ ]:
print(estudiantes["Maria Silva"])
print(estudiantes.get("Maria Silva"))

8.5
8.5

In [ ]:
print(estudiantes.items())

dict_items([('Maria Silva', 8.5), ('Fernanda Castro', 6.5), ('Juan Perez', 7.3), ('Rodrigo Feliz', 6.3), ('Juaan Lala', 2.5)])

In [ ]:
estudiantes.pop("Maria Silva")
estudiantes

{'Fernanda Castro': 6.5,
 'Juan Perez': 7.3,
 'Rodrigo Feliz': 6.3,
 'Juaan Lala': 2.5}

In [ ]:
print(estudiantes.keys())

dict_keys(['Fernanda Castro', 'Juan Perez', 'Rodrigo Feliz', 'Juaan Lala'])

In [ ]:
print(estudiantes.values())

dict_values([6.5, 7.3, 6.3, 2.5])

In [ ]:
persona= {
    "nombre":"Juan Perez",
    "edad":25,
    "materias":["Matematica","Literatura","Dibujo"]
}

print(persona)

{'nombre': 'Juan Perez', 'edad': 25, 'materias': ['Matematica', 'Literatura', 'Dibujo']}

In [ ]:
estudiante1 = {
    "nombre":"Juan Perez","edad":25
    }

estudiante2 = {
    "nombre":"Laura Fernandez","edad":28
    }

print(estudiante1)
print(estudiante2)

{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}

In [ ]:
lista_de_estudiantes= [
    {
    "nombre":"Juan Perez","edad":25
    },
    {
    "nombre":"Laura Fernandez","edad":28
    }
]

print(lista_de_estudiantes)

[{'nombre': 'Juan Perez', 'edad': 25}, {'nombre': 'Laura Fernandez', 'edad': 28}]

In [ ]:
lista_de_estudiantes[1]

{'nombre': 'Laura Fernandez', 'edad': 28}

In [ ]:
lista_de_estudiantes[1]["edad"]

28

In [ ]:
lista_de_estudiantes= [
    {
    "nombre":"Juan Perez","edad":25
    },
    {
    "nombre":"Laura Fernandez","edad":28
    }
]

n=0

while n < len(lista_de_estudiantes):
  print(lista_de_estudiantes[n])
  n+=1

for elemento in lista_de_estudiantes:
  print(elemento)

print("con cantidad definida")
for n in range(5):
  print(n)

print("con rango definido")
for n in range(2,8):
  print(n)

print("con intervalos")
for n in range(2,8,2):
  print(n)

{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}
{'nombre': 'Juan Perez', 'edad': 25}
{'nombre': 'Laura Fernandez', 'edad': 28}
con cantidad definida
0
1
2
3
4
con rango definido
2
3
4
5
6
7
con intervalos
2
4
6

In [ ]:
persona= {
    "nombre":"Juan Perez",
    "edad":25,
    "materias":["Matematica","Literatura","Dibujo"]
}

for clave,valor in persona.items():
  print(f"La clave es: {clave} y el valor es: {valor}")

for n in range(11):
  if n%2==0:
    print(n)

La clave es: nombre y el valor es: Juan Perez
La clave es: edad y el valor es: 25
La clave es: materias y el valor es: ['Matematica', 'Literatura', 'Dibujo']
0
2
4
6
8
10

In [ ]:
texto = "martIN bonino  de alUra "

print("Texto original:", texto)

print(texto.upper())
print(texto.lower())
print(texto.strip())

print("Texto sin los espacios repetidos en el medio")
print(texto.replace("  ", " "))

print(texto)

print(texto.lower().strip().replace("  ", " "))
print(texto)

texto = texto.lower().strip().replace("  ", " ")

print(texto)

Texto original: martIN bonino  de alUra
MARTIN BONINO  DE ALURA
martin bonino  de alura
martIN bonino  de alUra
Texto sin los espacios repetidos en el medio
martIN bonino de alUra
martIN bonino  de alUra
martin bonino de alura
martIN bonino  de alUra
martin bonino de alura

In [ ]:
nombres_1 = "   jUAn  pErez   "
nombres_2 = "mArIA   gONzaleZ   "
nombres_3 = "   rOdRiGo   saNchEz "
nombres_4 = "  ElisAbEtH   fLoReS"

In [ ]:
def corregir_texto(texto):
    texto_nuevo = texto.lower().strip().replace("  ", " ")
    print(texto_nuevo)

In [ ]:
corregir_texto(" LaURA fernandez  ")

laura fernandez

In [ ]:
corregir_texto(nombres_1)
corregir_texto(nombres_2)
corregir_texto(nombres_3)
corregir_texto(nombres_4)   #en este ejemplo el resultado sigue teniendo dos espacios sin corregir porque encontró 3espacios y no 2, asi que no lo corrigió

juan perez
maria  gonzalez
rodrigo  sanchez
elisabeth  flores

In [ ]:
nombres_1.split()

['jUAn', 'pErez']

In [ ]:
texto_corregido= " ".join(nombres_1.split())
print(texto_corregido)

jUAn pErez

In [ ]:
def corregir_texto(texto):
    texto_nuevo = texto.upper()
    lista_texto=texto_nuevo.split()
    #print(lista_texto)      se comentó para ver el resultado mas limpio en la siguiente celula de codigo
    texto_final=" ".join(lista_texto)
    print(texto_final)

In [ ]:
corregir_texto(nombres_1)
corregir_texto(nombres_2)
corregir_texto(nombres_3)
corregir_texto(nombres_4)

JUAN PEREZ
MARIA GONZALEZ
RODRIGO SANCHEZ
ELISABETH FLORES

In [ ]:
#SIMPLIFICACION DE CODIGO
def corregir_texto(texto):
    print(" ".join(texto.upper().split()))

In [ ]:
corregir_texto(" LaURA fernandez  ")

LAURA FERNANDEZ

In [ ]:
salones= ["Salón 1", "Salón 2", "Salón 3"]

In [ ]:
import random

def ubica_alumnos(nombre_alumno, lista_salones):
    salon_asignado = random.choice(lista_salones)

    dict_alumnos = {
        "nombre": nombre_alumno,
        "salon": salon_asignado
    }

    print(dict_alumnos)

In [ ]:
ubica_alumnos("Roberto Gonzalez",salones)

{'nombre': 'Roberto Gonzalez', 'salon': 'Salón 2'}

In [ ]:
def corrije_texto(texto):
    texto_nuevo = texto.upper()
    lista_palabras = texto_nuevo.split()
    nombre_final = " ".join(lista_palabras)
    return nombre_final    #SE USA RETURN PARA PODER TRAER INFORMACION FUERA DE OTRAS FUNCIONES

In [ ]:
nombre_optimizado = corrije_texto(nombres_2)
print(nombre_optimizado)

ubica_alumnos(nombre_optimizado, salones)

MARIA GONZALEZ
{'nombre': 'MARIA GONZALEZ', 'salon': 'Salón 3'}

# **DESAFÍO**

##crear una funcion que va a recibir como argumento una lista de emails y le va a pedir a una IA que los resuma en una sola linea

In [ ]:
cuerpos_emails = [
    "Hola, te envío el reporte de ventas del trimestre que solicitaste en la reunión. Quedo atento a tus comentarios.",
    "¡Tu suscripción ha sido renovada con éxito! El cargo de 9.99€ se ha aplicado a tu tarjeta terminada en 4421.",
    "¿Qué tal todo? Hace mucho que no hablamos. Podríamos quedar a tomar un café este jueves si tienes un hueco.",
    "Estimado alumno, le recordamos que el plazo para la entrega del proyecto final finaliza este viernes a medianoche.",

]

In [ ]:
def resumir_emails(cuerpos_emails):
  for numero, email in enumerate(cuerpos_emails):
    respuesta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"""Te voy a enviar el cuerpo de un email y necesito que lo resumas en una sola linea. Dejando clara la intencion de dicho correo.
         El correo es el siguiente:{email}""")

    print(f"E-mail N° {numero + 1}: {respuesta.text}")

In [ ]:
resumir_emails(cuerpos_emails)

E-mail N° 1: Aquí tienes el reporte de ventas trimestral solicitado.
E-mail N° 2: Aquí tienes algunas opciones, elige la que mejor se adapte al tono que buscas:

1.  **Tu suscripción ha sido renovada y el cargo aplicado.**
2.  **Confirmación de la renovación de tu suscripción y el cobro de 9.99€.**
3.  **Suscripción renovada con éxito y cargo a tu tarjeta.**
E-mail N° 3: Propone quedar para un café este jueves.
E-mail N° 4: Aquí tienes una opción:

**Recordatorio: El proyecto final se entrega este viernes a medianoche.**

#**IMPORTANDO GROQ**

In [ ]:
!pip install -q groq

In [ ]:
os.environ["GROQ_API_KEY"] = userdata.get["GROQ_API_KEY"]

In [ ]:
def resumir_emails(cuerpos_emails):
    lista_resumenes = []
    for numero, email in enumerate(cuerpos_emails):
        respuesta = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": f"""Te voy a enviar el cuerpo de un correo electrónico. Quiero que lo resumas en solo 1 línea,
indicando la intención de dicho correo. El correo es el siguiente: {email}"""
                }
            ]
        )
        texto= respuesta.choices[0].message.content

        print(f"E-Mail N° {numero + 1}: {respuesta.texto}")
        lista_resumenes.append(f"E-Mail N° {numero + 1}: {respuesta.texto}")

    return lista_resumenes

In [ ]:
resumir_emails(cuerpos_emails)

In [ ]:
lista_resumen=resumir_emails(cuerpos_emails)

In [ ]:
lista_resumen

In [ ]:
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
  for resumen in lista_resumen:
    archivo.write(resumen+ "\n")

In [ ]:
lista_lectura=[]
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
  for linea in archivo:
    lista_lectura.append(linea)

In [ ]:
lista_lectura

In [ ]:
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
  contenido= archivo.read()
  print(contenido)

In [ ]:
nueva_lista=[]
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
  nueva_lista=archivo.readlines()

In [ ]:
nueva_lista

In [ ]:
lista_lectura=[]
with open("lista-de-resumenes.txt", "w", encoding="utf-8") as archivo:
  for linea in archivo:
    lista_lectura.append(linea.strip())

In [ ]:
lista_lectura

#Desafío:

1. Crear un archivo .txt a partir de una lista de preguntas provenientes de python.
2. Leer esas preguntas desde el archivo .txt y guardarlas en una lista.
3. Obtener respuestas de un LLM para cada una.
4. Guardar los resultados en un nuevo archivo .csv
5. Leer el archivo .csv usando Pandas.

In [ ]:
import pandas as pd

In [ ]:
#Etapa 1
lista_de_preguntas = [
    "¿Cuál es la capital de Francia?",
    "¿En qué año se fundó Google?",
    "¿Cuál es el río más largo del mundo",
    "¿Cuál es el planeta más grande del sistema solar?",
    "¿Quién pintó la Mona Lisa?"
]

In [ ]:
#creacion de archivo txt, PASO #1. LISTO

with open("lista-de-preguntas.txt", "w", encoding="utf-8") as archivo:
  for pregunta in lista_de_preguntas:
    archivo.write(pregunta+ "\n")

In [ ]:
# PASO 2

lista_desafio=[]
with open("lista-de-preguntas.txt", "r", encoding="utf-8") as archivo:
  for linea in archivo:
    lista_desafio.append(linea.strip())

In [ ]:
print(lista_desafio)

['¿Cuál es la capital de Francia?', '¿En qué año se fundó Google?', '¿Cuál es el río más largo del mundo', '¿Cuál es el planeta más grande del sistema solar?', '¿Quién pintó la Mona Lisa?']

In [ ]:
#PASO 3
#Etapa 3
lista_de_diccionarios_respuestas = []

for pregunta in lista_desafio:
    respuesta = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
              "role": "user",
              "content": f"""te voy a enviar una pregunta y necesito que me duelvas la respuesta corta. pregunta:{pregunta}"""
             }
      ]

  )
  texto=respuesta.choices[0].message.content
  lista_de_diccionarios_respuestas.append({"pregunta":pregunta,"respuesta":texto})

AttributeError: 'Client' object has no attribute 'chat'

In [ ]:
#PASO 4

  with open("lista-de-respuestas.csv", "w", encoding="utf-8") as archivo:
    archivo.write("pregunta,respuesta\n")
    for diccionario in lista_de_diccionarios_respuestas:
      archivo.write(f"{diccionario['pregunta']},{diccionario['respuesta']}\n")

In [ ]:
#PASO 5

df=pd.DataFrame(lista_de_diccionarios_respuestas)

In [ ]:
df.to_csv("respuestas.csv", index=False)
df

In [ ]:
import pandas as pd
import random

In [ ]:
import pandas as pd
import random

# Definir posibles valores para las columnas
nombres_productos_posibles = [
    'Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Auriculares', 'Teclado', 'Mouse', 'Monitor', 'Impresora', "Altavoz",
    'Cámara', 'Disco Duro', 'Router', 'Webcam', 'Micrófono', 'Gafas VR', 'Consola', 'Control Remoto',"Proyector", "Bateria externa"
]
categorias_posibles = ['Electrónica', 'Hogar', 'Oficina', 'Entretenimiento', 'Accesorios']

# Seleccionar 10 nombres de productos únicos aleatoriamente
productos_elegidos = random.sample(nombres_productos_posibles, 10)

# Generar datos para las 10 filas
data = {
    'Nombre de producto': productos_elegidos,
    'Categoria': [random.choice(categorias_posibles) for _ in range(10)],
    'Precio': [round(random.uniform(50, 1500), 2) for _ in range(10)],
    'Stock': [random.randint(10, 100) for _ in range(10)]
}

# Crear el DataFrame
df_productos = pd.DataFrame(data)

# Mostrar el DataFrame
display(df_productos)

  Nombre de producto        Categoria   Precio  Stock
0              Mouse       Accesorios   656.40     37
1            Teclado            Hogar  1230.65     68
2          Proyector  Entretenimiento  1449.36     46
3           Gafas VR      Electrónica   383.73     64
4            Monitor            Hogar   643.67     29
5             Router            Hogar   553.16     70
6          Impresora      Electrónica   377.20     16
7             Laptop            Hogar   910.58     90
8        Auriculares      Electrónica   917.35     17
9         Disco Duro  Entretenimiento   344.99     74

In [ ]:
df_productos["Categoria"]

0         Accesorios
1              Hogar
2    Entretenimiento
3        Electrónica
4              Hogar
5              Hogar
6        Electrónica
7              Hogar
8        Electrónica
9    Entretenimiento
Name: Categoria, dtype: object

In [ ]:
df_productos["Categoria"].unique()

array(['Accesorios', 'Hogar', 'Entretenimiento', 'Electrónica'],
      dtype=object)

In [ ]:
set(df_productos['Categoria'])   #este es un diccionario porque tiene { }

{'Accesorios', 'Electrónica', 'Entretenimiento', 'Hogar'}

In [ ]:
#Aplicando filtros
df_productos[df_productos["Categoria"]=="Hogar"]

  Nombre de producto Categoria   Precio  Stock
1            Teclado     Hogar  1230.65     68
4            Monitor     Hogar   643.67     29
5             Router     Hogar   553.16     70
7             Laptop     Hogar   910.58     90

In [ ]:
#Aplicando filtros por cantidad
df_productos[df_productos["Stock"]>60]

  Nombre de producto        Categoria   Precio  Stock
1            Teclado            Hogar  1230.65     68
3           Gafas VR      Electrónica   383.73     64
5             Router            Hogar   553.16     70
7             Laptop            Hogar   910.58     90
9         Disco Duro  Entretenimiento   344.99     74

In [ ]:
df_productos.shape

(10, 4)

In [ ]:
#creamos una varibale donde almacenar el resultado del filtro
stock_mayor_60= df_productos[df_productos["Stock"]>60]
stock_mayor_60

  Nombre de producto        Categoria   Precio  Stock
1            Teclado            Hogar  1230.65     68
3           Gafas VR      Electrónica   383.73     64
5             Router            Hogar   553.16     70
7             Laptop            Hogar   910.58     90
9         Disco Duro  Entretenimiento   344.99     74

In [ ]:
stock_mayor_60.shape

(5, 4)

In [ ]:
df_productos[(df_productos["Categoria"]=="Electrónica") & (df_productos["Stock"]>70)]

Empty DataFrame
Columns: [Nombre de producto, Categoria, Precio, Stock]
Index: []

#**ILOC Y LOC**

In [ ]:
df_productos.iloc[2]   #iloc se utiliza para localizar por numero de indice mientras que loc se usa para localizar por nombre

Nombre de producto          Proyector
Categoria             Entretenimiento
Precio                        1449.36
Stock                              46
Name: 2, dtype: object

In [ ]:
df_productos.iloc[2:5]

  Nombre de producto        Categoria   Precio  Stock
2          Proyector  Entretenimiento  1449.36     46
3           Gafas VR      Electrónica   383.73     64
4            Monitor            Hogar   643.67     29

In [ ]:
df_productos.iloc[:5]

  Nombre de producto        Categoria   Precio  Stock
0              Mouse       Accesorios   656.40     37
1            Teclado            Hogar  1230.65     68
2          Proyector  Entretenimiento  1449.36     46
3           Gafas VR      Electrónica   383.73     64
4            Monitor            Hogar   643.67     29

In [ ]:
df_productos.iloc[2:]

  Nombre de producto        Categoria   Precio  Stock
2          Proyector  Entretenimiento  1449.36     46
3           Gafas VR      Electrónica   383.73     64
4            Monitor            Hogar   643.67     29
5             Router            Hogar   553.16     70
6          Impresora      Electrónica   377.20     16
7             Laptop            Hogar   910.58     90
8        Auriculares      Electrónica   917.35     17
9         Disco Duro  Entretenimiento   344.99     74

In [ ]:
df_productos= df_productos.set_index("Nombre de producto")
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   656.40     37
Teclado                       Hogar  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                       Hogar   643.67     29
Router                        Hogar   553.16     70
Impresora               Electrónica   377.20     16
Laptop                        Hogar   910.58     90
Auriculares             Electrónica   917.35     17
Disco Duro          Entretenimiento   344.99     74

In [ ]:
df_productos.loc["Mouse"]

Categoria    Accesorios
Precio            656.4
Stock                37
Name: Mouse, dtype: object

In [ ]:
df_productos.loc["Mouse":]

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   656.40     37
Teclado                       Hogar  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                       Hogar   643.67     29
Router                        Hogar   553.16     70
Impresora               Electrónica   377.20     16
Laptop                        Hogar   910.58     90
Auriculares             Electrónica   917.35     17
Disco Duro          Entretenimiento   344.99     74

In [ ]:
df_productos.loc[:"Monitor"]

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   656.40     37
Teclado                       Hogar  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                       Hogar   643.67     29

In [ ]:
df_productos.loc["Teclado":"Auriculares"]

                          Categoria   Precio  Stock
Nombre de producto
Teclado                       Hogar  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                       Hogar   643.67     29
Router                        Hogar   553.16     70
Impresora               Electrónica   377.20     16
Laptop                        Hogar   910.58     90
Auriculares             Electrónica   917.35     17

In [ ]:
df_productos.loc[["Teclado","Auriculares"],["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Teclado             1230.65     68
Auriculares          917.35     17

In [ ]:
hogar= df_productos[df_productos["Categoria"]=="Hogar"]

In [ ]:
df_productos.loc[hogar.index,["Precio","Stock"]]

                     Precio  Stock
Nombre de producto
Teclado             1230.65     68
Monitor              643.67     29
Router               553.16     70
Laptop               910.58     90

In [ ]:
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   656.40     37
Teclado                       Hogar  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                       Hogar   643.67     29
Router                        Hogar   553.16     70
Impresora               Electrónica   377.20     16
Laptop                        Hogar   910.58     90
Auriculares             Electrónica   917.35     17
Disco Duro          Entretenimiento   344.99     74

In [ ]:
df_productos.loc[hogar.index,"Categoria"]= "Casa"   #cambiando nombre de la categoria HOGAR a CASA
df_productos

                          Categoria   Precio  Stock
Nombre de producto
Mouse                    Accesorios   656.40     37
Teclado                        Casa  1230.65     68
Proyector           Entretenimiento  1449.36     46
Gafas VR                Electrónica   383.73     64
Monitor                        Casa   643.67     29
Router                         Casa   553.16     70
Impresora               Electrónica   377.20     16
Laptop                         Casa   910.58     90
Auriculares             Electrónica   917.35     17
Disco Duro          Entretenimiento   344.99     74

Desafío:

1.-Cargar un archivo .csv con feedback de clientes y crear un dataframe

2.-Usar un LLM para clasificar el sentimiento de cada feedback (positivo, negativo, neutro)

3.-Agregar esa clasificación al DataFrame

In [ ]:
import pandas as pd

In [ ]:
#PASO 1

df_reviews=pd.read_csv("/content/reviews.csv")

In [ ]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [ ]:
columna_de_reviews=df_reviews["reviewText"]

In [ ]:
columna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [ ]:
#PASO 2

lista_de_analisis=[]
for numero, review in enumerate(columna_de_reviews):
    respuesta = client_groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
                {
                    "role": "user",
                    "content": f""" Debes analizar la reseña que yo te envio y retornar un analisis de sentimiento. Debes responder
                    con: Positiva, Negativa o Neutra. Ejemplo:

                    Me encanto el producto -> Positiva
                    El producto no es nada especial -> Neutra
                    No me gusto el producto -> Negativa

                    Debes responder solamente una de esas tres opciones (Positiva, Neutra o Negativa) No agregues texto o explicaciones.

                    Reseña: {review}"""

                }

            ]
        )
    texto = respuesta.choices[0].message.content

    print(f"Review {numero}: {review} -> Sentimiento: {texto}")
    lista_de_analisis.append(texto)

In [ ]:
lista_de_analisis

In [ ]:
#PASO 3

df_reviews["Sentimiento"]= lista_de_analisis
df_reviews.head()

#**Gestion de Errores**

In [2]:
edad=int(input("Ingrese su edad"))

Ingrese su edad30

In [3]:
persona=6
persona2= "Juan,Pedro,Laura,Maria"
persona+persona2

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
try:
  edad=int(input("Ingrese su edad"))
except:
  print("No ingresaste un numero")

Ingrese su edadoli
Debes ingresar un numero

In [7]:
try:
  edad=int(input("Ingrese su edad"))
except ValueError as ve:
  print("No ingresaste un numero")
  print("El error es:",ve)

Ingrese su edaddd
No ingresaste un numero
El erros es: invalid literal for int() with base 10: 'dd'

In [11]:
try:
  edad=int(input("Ingrese su edad"))
  persona=6
  persona2= "Juan,Pedro,Laura,Maria"
  persona+persona2
except ValueError as ve:
  print("No ingresaste un numero")
  print("El erros es:",ve)
except TypeError as te:
  print("No puedes sumar un numero con un texto")
  print("El error es:",te)
finally:
  print("Finalizó la ejecución")

Ingrese su edadvv
No ingresaste un numero
El erros es: invalid literal for int() with base 10: 'vv'
Finalizó la ejecución

In [ ]:
df_reviews
df_reviews["Sentimiento"]

In [ ]:
df_reviews["Sentimiento"]=="Negativa"

In [ ]:
df_reviews_negativas=df_reviews["Sentimiento"]=="Negativa"
df_reviews_negativas

In [ ]:
reviews_negativas=df_reviews_negativas["reviewText"]
reviews_negativas

In [ ]:
reviews_negativas_unidas= "####".join(reviews_negativas)
reviews_negativas_unidas

In [ ]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por "####"
                 Quiero que encuentres *exactamente* 5 categorías diferentes para cada tipo de reclamo.
                 Quiero que retornes las cinco categorías como una lista de palabras separadas por comas, sin tildes y en minúsculas.
                 La respuesta debe ser solamente las cinco categorías, separadas por comas
                  Ejemplo:

                          "uso, calidad, duracion, estado, aspecto"

                          Reseña: {reviews_negativas_unidas}"""
        }
    ]
)
print(respuestas_cat.choices[0].message.content)

In [ ]:
categorias=respuestas_cat.choices[0].message.content

In [ ]:
lista_de_categorias=categorias.split(", ")
lista_de_categorias

#**JSON**

In [ ]:
{
  "name": "Chris",
  "age": 23,
  "address": {
    "city": "New York",
    "country": "America"
  },
  "friends": [
    {
      "name": "Emily",
      "hobbies": [
        "biking",
        "music",
        "gaming"
      ]
    },
    {
      "name": "John",
      "hobbies": [
        "soccer",
        "gaming"
      ]
    }
  ]
}

In [ ]:
respuestas_cat = client_groq.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": f"""Eres un analista de datos, te pasaré muchas reseñas separadas por "####"
              Quiero que encuentres *exactamente* 5 categorías diferentes para cada tipo de reclamo.
              Las categorías deben ser solo una palabra.
              Despues quiero que me retornes la respuesta en formato JSON con tres claves:
              - "review_original": Aquí va la review original;
              - "review_es": Reseña traducida al español;
              - "categoria": Categoria definida correspondiente a esa reseña.

              Ejemplo:

             {{"review_original": "I didn't like the color of the product"}}

             La respuesta debe ser SOLO y UNICAMENTE el texto en JSON

                 Reseñas: {reviews_negativas_unidas}"""
          }
       ]
    )
json_de_reviews_clasificadas=respuestas_cat.choices[0].message.content
print(json_de_reviews_clasificadas)

In [ ]:
import json

dic_reviews_negativas_clasificadas=json.loads(json_de_reviews_clasificadas)
dic_reviews_negativas_clasificadas

In [ ]:
len(dic_reviews_negativas_clasificadas)

In [ ]:
dic_reviews_negativas_clasificadas[2]